import Vue from 'vue'
import { Tabs, Tab, Checkbox, CheckboxGroup, Rate, Dialog, ActionSheet, Tabbar, TabbarItem, NavBar, Form, Field, Button, Toast, Loading, Search, Swipe, SwipeItem, Grid, GridItem, Icon } from 'vant'
Vue.use(Tabs)
Vue.use(Tab)
Vue.use(CheckboxGroup)
Vue.use(Checkbox)
Vue.use(Rate)
Vue.use(Dialog)
Vue.use(Icon)
Vue.use(ActionSheet)

Vue.use(GridItem)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)

Vue.use(Loading)
Vue.use(Toast)
Vue.use(Button)
Vue.use(Form)
Vue.use(Field)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
